version: 0.2
env:
  variables:
    PUBLIC_ECR_ALIAS: "s9l6w2o6"

batch:
  fast-fail: false
  build-list:
    - identifier: base10220
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "base"
          IMAGE_TAG: "10.22.0"
    - identifier: base1200Libgbm
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "base"
          IMAGE_TAG: "12.0.0-libgbm"
    - identifier: base12183
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "base"
          IMAGE_TAG: "12.18.3"
    - identifier: base12184
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "base"
          IMAGE_TAG: "12.18.4"
    - identifier: base12190
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "base"
          IMAGE_TAG: "12.19.0"
    - identifier: base14101
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "base"
          IMAGE_TAG: "14.10.1"
    - identifier: base14150
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "base"
          IMAGE_TAG: "14.15.0"
    - identifier: base14154
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "base"
          IMAGE_TAG: "14.15.4"
    - identifier: base1450
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "base"
          IMAGE_TAG: "14.5.0"
    - identifier: base1470
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "base"
          IMAGE_TAG: "14.7.0"
    - identifier: basemanjaro14120
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "base"
          IMAGE_TAG: "manjaro-14.12.0"

    - identifier: browserschrome65Ff57
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "chrome65-ff57"
    - identifier: browserschrome67
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "chrome67"
    - identifier: browserschrome67Ff57
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "chrome67-ff57"
    - identifier: browserschrome69
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "chrome69"
    - identifier: browsersnode10110Chrome75
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node10.11.0-chrome75"
    - identifier: browsersnode10160Chrome76
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node10.16.0-chrome76"
    - identifier: browsersnode10160Chrome77
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node10.16.0-chrome77"
    - identifier: browsersnode10160Chrome77Ff71
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node10.16.0-chrome77-ff71"
    - identifier: browsersnode10163Chrome80Ff73
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node10.16.3-chrome80-ff73"
    - identifier: browsersnode1021Chrome74
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node10.2.1-chrome74"
    - identifier: browsersnode11130Chrome73
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node11.13.0-chrome73"
    - identifier: browsersnode1200Chrome73
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node12.0.0-chrome73"
    - identifier: browsersnode1200Chrome73Ff68
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node12.0.0-chrome73-ff68"
    - identifier: browsersnode1200Chrome75
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node12.0.0-chrome75"
    - identifier: browsersnode12130Chrome78Ff70
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node12.13.0-chrome78-ff70"
    - identifier: browsersnode12130Chrome78Ff70Brave78
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node12.13.0-chrome78-ff70-brave78"
    - identifier: browsersnode12130Chrome80Ff73
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node12.13.0-chrome80-ff73"
    - identifier: browsersnode12130Chrome80Ff74
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node12.13.0-chrome80-ff74"
    - identifier: browsersnode12140Chrome79Ff71
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node12.14.0-chrome79-ff71"
    - identifier: browsersnode12141Chrome83Ff77
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node12.14.1-chrome83-ff77"
    - identifier: browsersnode12141Chrome85Ff81
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node12.14.1-chrome85-ff81"
    - identifier: browsersnode12161Chrome80Ff73
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node12.16.1-chrome80-ff73"
    - identifier: browsersnode12162Chrome81Ff75
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node12.16.2-chrome81-ff75"
    - identifier: browsersnode12180Chrome83Ff77
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node12.18.0-chrome83-ff77"
    - identifier: browsersnode12183Chrome83Ff77
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node12.18.3-chrome83-ff77"
    - identifier: browsersnode12183Chrome87Ff82
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node12.18.3-chrome87-ff82"
    - identifier: browsersnode12184Edge88
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node12.18.4-edge88"
    - identifier: browsersnode12190Chrome86Ff82
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node12.19.0-chrome86-ff82"
    - identifier: browsersnode1240Chrome76
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node12.4.0-chrome76"
    - identifier: browsersnode1260Chrome75
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node12.6.0-chrome75"
    - identifier: browsersnode1260Chrome77
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node12.6.0-chrome77"
    - identifier: browsersnode1281Chrome78Ff70
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node12.8.1-chrome78-ff70"
    - identifier: browsersnode1281Chrome80Ff72
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node12.8.1-chrome80-ff72"
    - identifier: browsersnode1310Chrome78Ff70
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node13.1.0-chrome78-ff70"
    - identifier: browsersnode1330Chrome79Ff70
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node13.3.0-chrome79-ff70"
    - identifier: browsersnode1360Chrome80Ff72
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node13.6.0-chrome80-ff72"
    - identifier: browsersnode1380Chrome81Ff75
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node13.8.0-chrome81-ff75"
    - identifier: browsersnode14101Edge88
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node14.10.1-edge88"
    - identifier: browsersnode14150Chrome86Ff82
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node14.15.0-chrome86-ff82"
    - identifier: browsersnode1470Chrome84
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node14.7.0-chrome84"
    - identifier: browsersnode8151Chrome73
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node8.15.1-chrome73"
    - identifier: browsersnode821Chrome73
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node8.2.1-chrome73"
    - identifier: browsersnode893Chrome73
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node8.9.3-chrome73"
    - identifier: browsersnode893Npm6101Chrome75
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node8.9.3-npm6.10.1-chrome75"
    - identifier: browsersnode893Npm6101Chrome76Ff68
      env:
        image: aws/codebuild/standard:5.0
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          IMAGE_REPO_NAME: "browsers"
          IMAGE_TAG: "node8.9.3-npm6.10.1-chrome76-ff68"

phases:
  pre_build:
    commands:
      - aws --version
      - echo Check if $IMAGE_TAG is in ECR...
      - ./find-ecr-image.sh $IMAGE_REPO_NAME $IMAGE_TAG -p
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - aws ecr-public get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin public.ecr.aws/$PUBLIC_ECR_ALIAS
  build:
    commands:
      - echo Building the Docker image...          
      - cd $IMAGE_REPO_NAME/$IMAGE_TAG
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG public.ecr.aws/$PUBLIC_ECR_ALIAS/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/$PUBLIC_ECR_ALIAS/$IMAGE_REPO_NAME:$IMAGE_TAG