version: 0.2

env:
  variables:
    PUBLIC_ECR_ALIAS: "s9l6w2o6"
    IMAGE_REPO_NAME: "browsers"
    IMAGE_TAG: "node12.18.3-chrome87-ff82"

phases:
  pre_build:
    commands:
      - aws --version
      - echo Check if $IMAGE_TAG is in ECR...
      - ./find-ecr-image.sh $IMAGE_REPO_NAME $IMAGE_TAG -p
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - aws ecr-public get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin public.ecr.aws/$PUBLIC_ECR_ALIAS
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - cd $IMAGE_REPO_NAME/$IMAGE_TAG
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG public.ecr.aws/$PUBLIC_ECR_ALIAS/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/$PUBLIC_ECR_ALIAS/$IMAGE_REPO_NAME:$IMAGE_TAG