# info on building Docker images on Circle
# https://circleci.com/docs/2.0/building-docker-images/
version: 2
jobs:
  build:
    machine: true
    environment:
      DOCKER_NAME: cypress/base
      DOCKER_TAG: 12.14.0
    steps:
      - checkout
      - run:
          name: Check if image exists
          # using https://github.com/mishguruorg/docker-image-exists
          # to check if Docker hub has the image already
          command: |
            if npx docker-image-exists --quiet --repo $DOCKER_NAME/$DOCKER_TAG; then
              echo Found image $DOCKER_NAME/$DOCKER_TAG
              circleci-agent step halt
            else
              echo Did not find Docker image $DOCKER_NAME/$DOCKER_TAG
            fi
      - run:
          name: build $DOCKER_NAME/$DOCKER_TAG
          # command: ./build.sh
          command: |
            docker build -t $DOCKER_NAME/$DOCKER_TAG
          working_directory: base/12.14.0
workflows:
  version: 2
  build-base-images:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - add-circle-build
