# info on building Docker images on Circle
# https://circleci.com/docs/2.0/building-docker-images/
version: 2
jobs:
  build:
    machine: true
    # docker:
    #   - image: buildpack-deps:trusty
    steps:
      - checkout
      # only required if using a Docker image
      # - setup_remote_docker
      - run:
          name: build 12.14.0
          command: ./build.sh
          # command: |
          #   docker build -t cypress/base:12.14.0
          working_directory: base/12.14.0
workflows:
  version: 2
  build-base-images:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - add-circle-build
